package com.senior.devrecruitment.enums;

public enum AreaAconselhavel {

    DESENVOLVIMENTO_WEB, DESKTOP, DESENVOLVIMENTO_DESKTOP, BACKEND, FRONTEND, FULL_STACK, MOBILE,
    CYBERSECURITY, BIGDATA, IA, DEVOPS, CIENCIA_DE_DADOS;
}
